[WIP][BSP-138]health-check endpoint
jwa-lab/airlock pull request #23
Opened 2021-08-04 15:51 UTC by tkjwa

The AWS load balancer requires a health check endpoint to make sure the services behind the load balancer are alive.

- [x] add new endpoint
- [x] add test for success
- [ ] add test for failure

2021-08-04 21:07 UTC, podefr commented on src/index.ts
> +        app.get("/health-check", cors(), healthCheck(natsConnection));
1. do we need to distinguish between readiness and liveness? I'm curious about our overall strategy for determining if a container should be restart and receive traffic
2. do we need cors or can we remove it?

2021-08-04 21:08 UTC, podefr commented on tests/airlock.test.js
> +            let response = await axios.get(`${SERVER_URL}/health-check`);
nit: `i -> I` and let's use const if we don't reassign a var :)

2021-08-04 21:08 UTC, podefr commented on src/middlewares/healthCheck.ts
> +    return async function (req: Request, res: Response): Promise<void> {
thanks so much for getting started on the health probes!

2021-08-09 08:36 UTC, tkjwa commented
I ended up with a NatsConnectionMonitor with less responsabilities than the initial ConnectionManager.
We need to think about the test with a failing connection and how to adapt our test suite to this use case

2021-08-11 07:45 UTC, 0x103 approved these changes

2021-08-11 07:49 UTC, 0x103 requested changes
Just need to bump the version in the package.json.

2021-08-12 09:13 UTC, podefr approved these changes

2021-08-12 09:14 UTC, 0x103 approved these changes

2021-08-12 09:32 UTC, merged